### ISSUE TITLE
Design: 공통 컴포넌트 추가 구현

### ISSUE THREAD

**Issue by GraceKim527** [LikeLion-12th-SKHU/LikeLion-12th-TEAM02-FE#17]
## ✨ About Issue ✨

UI/UX적으로 필요한 컴포넌트들을 구현합니다.

<br>

## ✅ Todo

- [x] 로딩창 컴포넌트 만들기
- [x] 헤더 컴포넌트 변경할 부분 변경
- [x] 메뉴바 다시 설정
- [x] 웹 접속 방지 컴포넌트 만들기
