### ISSUE TITLE
Style: 공통 컴포넌트 만들기

### ISSUE THREAD

**Issue by GraceKim527** [LikeLion-12th-SKHU/LikeLion-12th-TEAM02-FE#2]
## ✨ About Issue ✨

공통으로 사용될 컴포넌트들을 제작합니다. 

<br>

## ✅ Todo

- [x] 공통 컴포넌트 제작
- [x] 웹앱을 위한 모바일 화면 최적화
- [x] 공통 스타일링 제작
