### ISSUE TITLE
Test: QA 시트

### ISSUE THREAD

**Issue by GraceKim527** [LikeLion-12th-SKHU/LikeLion-12th-TEAM02-FE#41]
## ✨ About Issue ✨

테스트를 진행하며 필요한 QA를 적고 해결합니다. 

## ✅ Todo

⭐️의 개수는 중요도 표시

- [x] ⭐️⭐️⭐️ 친구 요청에서 수락을 눌러도 사라지지 않는 현상 수정 필요
- [x] ⭐️⭐️⭐️ 친구 요청에 거절 버튼이 없음.
- [x] ⭐️ 캘린더에서 추가버튼을 좀 줄이는 건 어떨까.
- [x] ⭐️⭐️ 내 정보에서 이름 부분 cursor pointer, 이메일에 밑줄 쳐져 있는 부분 수정 필요
- [x] ⭐️⭐️ 감정 통계에서 뒤로가기 화살표 누르면 메인으로 이동이 불가한 현상 수정 필요
- [x] ⭐️ 404페이지에서 홈으로 이동하는 버튼 만들면 좋을 듯.
