### ISSUE TITLE
Fix: QA 시트 2차

### ISSUE THREAD

**Issue by GraceKim527** [LikeLion-12th-SKHU/LikeLion-12th-TEAM02-FE#47]
## ✨ About Issue ✨

QA 시트 2차를 작성합니다.

## ✅ Todo

- [ ] 이메일이 길어서 삭제 버튼이 작아지는 현상
- [ ] 카카오 로그아웃 시 실패 메시지가 뜨는 현상 
- [ ] 구글 로그인하려고 클릭하면 로그인 후 이용이 가능하다고 뜨는 현상
- [ ] 로그아웃 시 로그인 후 사용 가능하다는 문구가 뜨는 현상
- [ ] 회원탈퇴 시 405 에러 발생
