### ISSUE TITLE
Design: Main 디자인

### ISSUE THREAD

**Issue by SuKyeong2002** [LikeLion-12th-SKHU/LikeLion-12th-TEAM02-FE#5]
## ✨ About Issue ✨
- 메인 화면 디자인
<br>

## ✅ Todo
- [x] 일일 출석 구현 
- [x] 오브제 (보유 오브제 리스트) 구현
- [x] 오브제 (오브제 꾸미기) 구현
