### ISSUE TITLE
Design: 설정 화면 디자인

### ISSUE THREAD

**Issue by SuKyeong2002** [LikeLion-12th-SKHU/LikeLion-12th-TEAM02-FE#9]
## ✨ About Issue ✨
- 설정 (사용자 정보 조회) 화면 디자인
- 설정 (사용자 이름 변경) 화면 디자인
- 설정 (개발자 피드백) 화면 디자인
- 설정 (로그아웃) 화면 디자인
- 설정 (회원탈퇴) 화면 디자인
<br>

## ✅ Todo
- [x] 설정 (사용자 정보 조회) 기능 구현
- [x] 설정 (사용자 이름 변경) 기능 구현
- [x] 설정 (개발자 피드백) 기능 구현
- [x] 설정 (로그아웃) 기능 구현
- [x] 설정 (회원탈퇴) 기능 구현
